name: run-script
on: pull_request

env:
  PATH: "/usr/local/wx3.2.1-gtk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

jobs:
  ubuntu-2404-smoke-deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wxWidgets
        run: |
          scripts/build-wx3.2.1-gtk.sh

      - name: Build Lisaem
        run: |
          ./build.sh clean build
